Module6 task1
htmlacademy-ecmascript/643469-big-trip-12 pull request #9
Opened 2020-08-30 19:18 UTC by StasRomanov

2020-08-31 06:53 UTC, babtshe requested changes

2020-08-31 06:53 UTC, babtshe commented on package.json
> +  "type": "big_trip",
для чего нужна эта правка?

2020-08-31 06:53 UTC, babtshe commented on src/mock/bonusOption.js
> +    prices: [30, 10, 15, 40],
названия опций и ценники хорошо хранить в отдельной структуре данных, а руками их не нужно заводить. 
Кроме того, цену хорошо привязать к названию явно.

2020-08-31 06:53 UTC, babtshe commented on src/presenter/waypoint.js
> +  _renderBonusOptionEditMode(waypoint) {
есть смысл подумать, как отвязать рендеринг от режима, чтобы не плодить кучу однотипных функций.

2020-08-31 06:53 UTC, babtshe commented on src/util/data-function.js
> +};
хорошо бы избавиться от магии, проверку упростить, а функцию назвать в соответствии с критериями.

2020-08-31 06:53 UTC, babtshe commented on src/util/data-function.js
> +};
этот метод не должен знать, что ему подсунули тестовые данные, и должен работать с данными как с реальными.

2020-08-31 06:53 UTC, babtshe commented on src/view/site-edit-event.js
> +  }
для чего нужна эта проверка?

2020-08-31 06:53 UTC, babtshe commented on src/view/site-edit-event.js
> +    mock.forEach((item) => {
вьюшка про моки ничего не должна знать.

2020-09-01 06:16 UTC, StasRomanov commented on package.json
> +  "type": "big_trip",
случайная автозамена

2020-09-01 06:24 UTC, StasRomanov commented on src/view/site-edit-event.js
> +  }
если введет буквы в поле с ценой выдаст 0

2020-09-02 06:36 UTC, babtshe approved these changes

2020-09-02 06:36 UTC, babtshe commented on src/util/data-function.js
> +  if (typeof str === `string`) {
см [критерий](https://up.htmlacademy.ru/ecmascript/12/criteries#d10)

2020-09-02 06:36 UTC, merged